### PR TITLE
Placeholder Pages + Navi and Tests (Fixed)

### PR DESCRIPTION
**Pull request by PeakFiction**
Third time's the charm! Hey gang, back at it again with another pull requests. This time I've fixed the tests and the coverage. Please check again, I've checked it and checked it and it comes out all good on the tests, however if there's anything wrong with the sonarcloud, I'll pull the pull request, don't mind commenting if you'd like.

### CODE REVIEW

**Comment by cl4ytn** [comment]
Nice work. Once this is fixed it should be ready. I think you can directly fix it and push to this branch and the PR will be updated without you having to close and reopen it.
image

**Review by cl4ytn — APPROVED** [review]
All checks passed, looks ready to merge.

**Review by PascalPahlevi — APPROVED** [review]
Everything looks good. Great job Duden.

**Comment by PeakFiction** [comment]
Sorry for lots of Pull Requests, I didn't know that you just need to commit to modify your pull request

**Pull request merged**
