### PR TITLE
Feature/edit profile back end merge to dev

### PR DESCRIPTION
**Pull request by samuelcodingjourney**
## Changes
- Implemented EditProfile component with form for updating user information
- Added password change functionality within the profile update
- Implemented error handling for API calls and form validation
- Updated UserService and UserServiceImpl to handle profile updates
- Enhanced test coverage for EditProfile, validationUtils, and App components

## Implementation Details
- The EditProfile component now fetches user data and allows updates to username, email, and password
- Password changes require both old and new passwords
- Added comprehensive error handling for API calls and form validation
- Updated UserService to include the new updateUser method signature

## Testing
- Added extensive unit tests for EditProfile component
- Improved test coverage for validationUtils
- Updated App.test.js to properly test routing

### CODE REVIEW

**Comment by PeakFiction** [comment]
There's 1 test that still failed, can you fix it? Thanks

**Review by cl4ytn — COMMENTED** [review]
Even though the test isnt yours, I think we should try to fix it before we merge to dev.

**Review by Sirered — CHANGES_REQUESTED** [review]
Let's fix this test fist

**Review by Sirered — APPROVED** [review]
Tests have been fixed, you have already demoed that the feature itself works. We'll resolve the degradation of the form's look that we saw earlier by branching from dev again

**Pull request merged**
