### PR TITLE
XSS Prevention Implementation on Edit User Organization Profile

### PR DESCRIPTION
**Pull request by PascalPahlevi**
Further enhancements for improved security, primarily focusing on XSS (Cross-Site Scripting) prevention across form fields in the EditUserOrgProfile component were implemented:

New Features:
- Implemented a sanitization utility using DOMPurify to clean user inputs in critical fields (e.g., name, username, email, position).

- Sanitization targets potentially harmful characters and HTML tags, allowing only plain text input for fields that do not require HTML content.

- Prevents malicious content from being saved to or displayed from the database, thereby reducing the risk of script execution.

### CODE REVIEW

**Review by samuelcodingjourney — APPROVED** [review]
Good job on the implementation. For future reference please keep in mind the code quality issues.

**Review by mariagrizelda — APPROVED** [review]
Nice work on adding XSS prevention! The code meets high standards for quality and security, with no new issues detected, full coverage on the new code, and no duplications

**Review by cl4ytn — APPROVED** [review]
Nice work on improving the security. It seems like your code effectively cleans input. I like how you modularized the sanitization so that we can implement this across the app.

**Review by PeakFiction — APPROVED** [review]
Good job Pascal, it seems my components have done you well now has it?

**Pull request merged**
